### ISSUE TITLE
lita-stock unable to retrieve stock information

### ISSUE THREAD

**Issue by jsandova** [webdestroya/lita-stocks#2]
I'm getting the following error when using the lita-stock plugin. It was working fine up until last week.

Sorry, but there was a problem retrieving stock information.

**Comment by blysik** [comment]
URL changed.  Needs to use something like this now:

'https://finance.google.com/finance?q=AAPL&output=json'

**Comment by webdestroya** [comment]
Would you be willing to make a PR for this?

**Comment by webdestroya** [comment]
Thank you @BlakeMesdag ! I just released version `0.1.0` with your changes!
